360Controller/360Controller

360Controller/Info.plist
This patch adds additional devices to the wired driver.
=> Add Additional Devices

Pref360Control/en.lproj/Pref360ControlPref.xib
I added a tabbed view to the Prefpane.
- I decided to use a tab-less tabbed view since it doesn't broke the original layout. (I don't want to scale the controller artwork again, it take me about an hour each time). 
- There's a segmented control to pilot the tabbed view, be sure to add a segment when you add a tab.
- I can make a custom segmented control if you want but you'll have to wait a bit.
=> Prefpane is now tabbed.

Readme.md
A place where people can list their success or non-success with using the 360 controller for different games
=> Added link in the readme to the games wiki page

Install360Controller/Scripts/upgrade.sh, Pref360Control/Pref360ControlPref.h, Pref360Control/Pref360ControlPref.m, Pref360Control/en.lproj/Pref360ControlPref.xib
I created a new branch with some UI changes:
* removed the about popover
* included an about tab so we can have more space to put the proper credits
---
I was about to create a new tab to include **Disable** and **Uninstall** buttons, and other misc options but I am not sure how it should look like, So I created this pull request to discuss these ui changes.
*The important question is:*
**Any thoughts about how these new UI elements should look like?**
My random thoughts:
* a new "Advanced" tab with this kind of stuff
* squeeze these options in the about menu.
* rename the deadzone menu to "Advanced" and cram that there too.
=> Some UI Changes

Wireless360Controller/Wireless360Controller.cpp
Quick fix for wireless 360 controller issues.
=> Remove wireless remapping

360Controller/Info.plist
=> Add HoriPadOne

360Controller/Controller.cpp, 360Controller/Controller.h, 360Controller/Info.plist, 360Controller/_60Controller.cpp, 360Controller/_60Controller.h
=> Fix Xbox One fight sticks and new devices

360Controller/Info.plist
#276 Controller added to plist
=> Added afterglow gamepad

360Controller/Info.plist
Added support to the EA Sports Xbox Controller
=> Added PDPEASports device

360Controller/Controller.cpp
Just making a pull request so I can squash a bunch of my useless commits. Sorry for the emails.
=> Add Racing Wheel Support

Readme.md
=> Update Readme.md's supported controllers

360Controller/Info.plist
=> Added Elecom JCU3613M

360Controller/Info.plist
It's really just another variant of their xbox 360 model, but with a new product id, I believe.
=> Added another device (Rock Candy PS3 Controller)

360Controller/Info.plist
madcatz beat pad added, already convert the hex to decimal in the file as i observed in the other devices.
=> Madcatbeatpad

360Controller/Info.plist
Guitar Hero live guitar ( RedOctane) 
device description added!
=> info.plist new device

360Controller/Info.plist
MADCATZ 360 MC2 added!
issue #761
=> new device added

Readme.md
download 0.16.15 or earlier =>
download 0.16.5 or earlier
=> Correct Readme typo

360 Driver.xcodeproj/project.pbxproj, 360Controller/zh-Hans.lproj/InfoPlist.strings, 360Daemon/zh-Hans.lproj/InfoPlist.strings, 360Daemon/zh-Hans.lproj/Localizable.strings, Feedback360/zh-Hans.lproj/InfoPlist.strings, Pref360Control/zh-Hans.lproj/InfoPlist.strings, Pref360Control/zh-Hans.lproj/Localizable.strings, Pref360Control/zh-Hans.lproj/Pref360ControlPref.strings, Wireless360Controller/zh-Hans.lproj/InfoPlist.strings, WirelessGamingReceiver/zh-Hans.lproj/InfoPlist.strings
I have fixed the issue， please have a look
=> add Simplified Chinese localization

360Controller/Info.plist, Pref360Control/zh-Hans.lproj/Pref360ControlPref.strings, Readme.md
This may fix #848,  just maybe, but I don't know.
=> update Simplified Chinese localization

360Controller/Info.plist
Ardwiino guitar hero controller adaptor added!
https://github.com/sanjay900/Ardwiino
=> Add ardwiino to info.plist

360Controller/ChatPad.cpp, 360Controller/Controller.cpp, 360Controller/_60Controller.cpp, Wireless360Controller/Wireless360Controller.cpp, WirelessGamingReceiver/WirelessGamingReceiver.cpp
Should be an initial fix for #942
=> Initial maybe fix for Catalina loading.

Feedback360/Feedback360.cpp, WirelessOneController/WirelessOneController.cpp, WirelessOneController/WirelessOneController.h, WirelessOneController/WirelessOneDongle.cpp, WirelessOneController/WirelessOneDongle.h, WirelessOneController/WirelessOneMT76.cpp
Initial rumble implementation for wireless Xbox One controllers.
=> Add wireless controller rumble
